<MyGridLayout>

	name: name
	composer: composer
	piece: piece

	GridLayout:
		cols:1
		size: root.width, root.height

		GridLayout:
			cols:2

			Label:
				text:"Name"
			TextInput:
				id: name
				multiline:False

			Label:
				text:"Fave Composer"
			TextInput:
				id: composer
				multiline:False

			Label:
				text:"Fave Piece"
			TextInput:
				id: piece
				multiline:False

		Button:
			text: "Submit"
			font_size: 32
			on_press: root.press()